#!/bin/bash

thisdir=$(cd $(dirname $BASH_SOURCE); pwd)


opt_error=0
np=1
ppn=
envs=
hostfile=
dry_run=
mca_opts=
while getopts "df:m:n:c:x:" flag; do
    case $flag in
        \?) opt_error=1; break;;
        f) hostfile="-hostfile $OPTARG";;
        n) np="$OPTARG";;
        c) ppn="-ppn $OPTARG";;
        x) envs="$envs -x $OPTARG";;
        d) dry_run=1;;
        m) mca_opts="$mca_opts --mca $OPTARG";;
    esac
done

shift $(( $OPTIND - 1 ))

# report option error 
if [ "$opt_error" == "1" -o "$*" = "" ]; then
    echo >&2 "Usage: 
    $0 
        [-n <# of MPI processes>]
        [-x <env>]
        [-f <hostfile>]
        [-d] (dry run)
        [-m <MPI mca parameters>]
        <program> [<args>]"
    exit 1
fi

# set environment variables
if [ "$steal_type" != "" ]; then
    envs="$envs -x MADM_STEAL_TYPE=$steal_type"
fi
if [ "$join_type" != "" ]; then
    envs="$envs -x MADM_JOIN_TYPE=$join_type"
fi

disable_aslr="$thisdir/madm_disable_aslr"
if [ "$(uname -s)" = "Darwin" ]; then
    disable_aslr=""
fi

# run or dry run
export MADM_RUN__=1
params="-n $np $ppn $envs $hostfile $mca_opts"
cmd="mpirun $params $disable_aslr $@"

# echo "$params"

if [ "$dry_run" == "" ]; then
    $cmd
else
    echo $cmd
fi
